
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://wmsmysql:3306/wmsd?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Tokyo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2345
    type: com.zaxxer.hikari.HikariDataSource
