
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://192.168.2.186:3306/wms?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql123
    type: com.zaxxer.hikari.HikariDataSource
