
server:
  address: 0.0.0.0
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://mysqldb-dev-seisoul.ckzodngsuzsb.ap-northeast-1.rds.amazonaws.com:3306/wmsd?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Tokyo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 87654321
    type: com.zaxxer.hikari.HikariDataSource
