
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/wms?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Tokyo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mysql123
    type: com.zaxxer.hikari.HikariDataSource
